"""Input records, parameters and output records of the MRP engine.

Everything here is a plain dataclass so the engine stays independent from pandas, the
database layer and the API layer.  Quantities are floats (units may be KG or M).
"""
from __future__ import annotations

import datetime as dt
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Literal


# =============================================================================
# Reference data
# =============================================================================
@dataclass
class Article:
    article_id: str
    designation: str = ""
    unit: str = "PCE"
    family: str = ""
    planner: str = ""
    coverage_target_days: int = 7
    alert_red_days: int = 3
    alert_yellow_days: int = 7
    overstock_days: int = 30
    safety_stock_qty: float = 0.0
    lot_policy: Literal["coverage", "poq", "fixed_lot"] = "coverage"
    order_cycle_days: int = 7
    fixed_lot_qty: float = 0.0
    active: bool = True
    service_rate_tracked: bool = False
    dhrq: str = ""
    # per-ISO-week overrides of the stock policy: {"2026-W40": {"coverage_target_days": 10, ...}}
    weekly: dict[str, dict[str, float]] = field(default_factory=dict)

    def param_at(self, name: str, day: dt.date) -> float:
        """Value of a stock-policy parameter on ``day`` (weekly override, else the article value)."""
        if self.weekly:
            y, w, _ = day.isocalendar()
            week = self.weekly.get(f"{y}-W{w:02d}")
            if week and name in week:
                return week[name]
        return getattr(self, name)


WEEKLY_FIELDS = ("coverage_target_days", "alert_red_days", "alert_yellow_days", "overstock_days",
                 "safety_stock_qty", "order_cycle_days")


@dataclass
class Supplier:
    supplier_id: str
    name: str = ""
    country: str = ""
    contact: str = ""
    delivery_weekdays: frozenset[int] = frozenset({1, 2, 3, 4, 5})
    calendar_id: str = "DEFAULT"
    active: bool = True


@dataclass
class SupplierLink:
    """Article ↔ supplier sourcing rule (MOQ, packaging, lead time, quota)."""

    article_id: str
    supplier_id: str
    moq: float = 0.0
    pack_qty: float = 0.0          # "PLA" – packaging / rounding quantity
    lead_time_days: int = 10       # working days
    quota_pct: float = 100.0
    priority: int = 1
    active: bool = True


@dataclass
class Program:
    program_id: str
    name: str = ""
    family: str = ""
    active: bool = True


@dataclass
class BomLine:
    program_id: str
    article_id: str
    qty_per: float
    unit: str = "PCE"
    scrap_pct: float = 0.0
    valid_from: dt.date | None = None
    valid_to: dt.date | None = None


# =============================================================================
# Facts
# =============================================================================
@dataclass
class PdpLine:
    """Weekly production plan (PDP) for one program and one ISO week."""

    program_id: str
    week_start: dt.date   # Monday
    qty: float
    version: str = ""


@dataclass
class ActualLine:
    """Actual daily production reported for a program (overrides the plan for that day)."""

    program_id: str
    date: dt.date
    qty: float


class OrderType(str, Enum):
    FIRM = "FIRM"          # confirmed schedule line / purchase order (DELJIT, PO)
    FORECAST = "FORECAST"  # forecast schedule line (DELFOR)
    PLANNED = "PLANNED"    # planned in the app, not sent to the supplier
    PROPOSAL = "PROPOSAL"  # generated by the engine


class OrderStatus(str, Enum):
    OPEN = "OPEN"
    PARTIAL = "PARTIAL"
    RECEIVED = "RECEIVED"
    CLOSED = "CLOSED"        # closed short: remainder will not be delivered
    CANCELLED = "CANCELLED"


@dataclass
class OrderLine:
    order_id: str
    article_id: str
    supplier_id: str | None
    expected_date: dt.date
    qty_ordered: float
    qty_received: float = 0.0
    order_type: OrderType = OrderType.FIRM
    status: OrderStatus = OrderStatus.OPEN
    source: str = "ERP"  # ERP | APP | SCENARIO | PROPOSAL
    order_date: dt.date | None = None
    note: str = ""

    @property
    def qty_open(self) -> float:
        if self.status in (OrderStatus.RECEIVED, OrderStatus.CLOSED, OrderStatus.CANCELLED):
            return 0.0
        return max(0.0, self.qty_ordered - self.qty_received)


@dataclass
class Receipt:
    receipt_id: str
    article_id: str
    receipt_date: dt.date
    qty: float
    supplier_id: str | None = None
    order_id: str | None = None
    source: str = "ERP"


@dataclass
class Movement:
    """Stock adjustment (inventory count, scrap, transfer…) dated after the snapshot."""

    movement_id: str
    article_id: str
    date: dt.date
    qty: float
    movement_type: str = "INVENTORY_ADJUSTMENT"
    source: str = "ERP"
    comment: str = ""


@dataclass
class SimCell:
    """One editable cell of the simulation grid: a signed stock **adjustment** typed by the planner.

    Any date is accepted: dated on or before the reference day it corrects the reference stock
    (the ERP stock is often wrong and the app never writes to the ERP), dated later it is a
    movement known in advance (planned scrap, transfer…).
    """

    article_id: str
    date: dt.date
    kind: Literal["adjustment"]
    qty: float
    source: str = "MANUAL"   # MANUAL | IMPORT
    note: str = ""


@dataclass
class PlanLine:
    """One delivery line of the planner's **delivery plan** (the only object the planner edits).

    * ``order_id`` set: the line *overrides* the ERP order (delivery slot) of that id in the plan
      layer – date and/or quantity changed, order split in several lines (same id), or quantity 0
      (nothing expected from it).  A forecast slot id turns the forecast into a plan line;
    * ``order_id`` None: a free line (stop-gap delivery, delivery outside any order, accepted CBN
      proposal).  A free line whose date is past simply expires.
    """

    line_id: str
    article_id: str
    date: dt.date
    qty: float
    order_id: str | None = None
    supplier_id: str | None = None
    source: str = "MANUAL"    # MANUAL | IMPORT | CBN
    note: str = ""


@dataclass
class StockSnapshot:
    article_id: str
    snapshot_date: dt.date      # stock known at the END of this day
    qty_on_hand: float
    qty_blocked: float = 0.0


@dataclass
class Dataset:
    """Everything the engine needs, as plain records."""

    articles: list[Article]
    suppliers: list[Supplier]
    links: list[SupplierLink]
    programs: list[Program]
    bom: list[BomLine]
    pdp: list[PdpLine]
    actuals: list[ActualLine]
    orders: list[OrderLine]
    receipts: list[Receipt]
    movements: list[Movement]
    stock: list[StockSnapshot]
    holidays: list[dt.date] = field(default_factory=list)
    cells: list[SimCell] = field(default_factory=list)      # adjustments typed in the grid
    plan: list[PlanLine] = field(default_factory=list)      # delivery plan lines
    meta: dict[str, Any] = field(default_factory=dict)


# =============================================================================
# Parameters
# =============================================================================
@dataclass
class EngineParams:
    """All business rules that are configurable (see docs/regles_metier.md)."""

    as_of: dt.date | None = None                  # default: max stock snapshot date + 1
    horizon_days: int = 120                       # projection horizon after as_of
    history_days: int = 14                        # days before as_of kept in the output series
    working_weekdays: tuple[int, ...] = (1, 2, 3, 4, 5)

    # Demand
    spread_rounding: Literal["none", "exact", "per_day"] = "exact"
    # actual_then_remainder [default]: past days = reported actual production ; current ISO week =
    # remainder of the weekly PDP (PDP − actuals already reported) spread over the remaining open
    # days ; later weeks = PDP.  Other modes: actual_then_plan, plan_only, actual_only.
    production_mode: Literal["actual_then_remainder", "actual_then_plan", "plan_only", "actual_only"] = "actual_then_remainder"
    missing_actual_policy: Literal["plan", "zero"] = "zero"   # past day without actual report: plan or 0
    consumption_offset_days: int = 0              # <0: components consumed before the production day

    # Supply – two stock layers: ERP (firm orders as is) and Plan (the planner's delivery plan)
    firm_sources: tuple[str, ...] = ("FIRM",)                    # order types counted in the ERP stock
    forecast_date_policy: Literal["actual", "week_monday"] = "actual"  # forecast orders on their date or on the Monday
    include_proposals_in_plan: bool = True        # the CBN complement is part of the plan stock
    orders_source: Literal["merged", "erp", "app"] = "merged"

    # Coverage / stock policy
    shortage_policy: Literal["backlog", "lost"] = "backlog"  # unserved demand: carried forward or lost
    coverage_unit: Literal["calendar", "working"] = "calendar"
    coverage_tie_rule: Literal["covered", "not_covered"] = "covered"
    target_policy: Literal["coverage_days", "safety_qty", "max"] = "max"

    # Proposals (net requirements, "Complément CBN"): computed on every run on the plan stock
    generate_proposals: bool = True
    proposal_placement: Literal["working_days", "monday"] = "working_days"  # delivery on any working day or Mondays only
    shortfall_tolerance_days: int = 0             # ignore dips under target that recover within N working days without shortage
    frozen_days: int = 0
    respect_lead_time: bool = False               # True: never propose a delivery before as_of + lead time
    delivery_shift: Literal["earlier", "later"] = "earlier"
    sourcing_policy: Literal["quota", "priority"] = "quota"
    proposal_lookahead_days: int | None = None   # None: whole horizon

    # Alerts
    stockout_lookahead_days: int | None = None    # None: whole horizon
    firm_horizon_days: int = 28                   # firm-flow stockouts beyond this are informational

    # Display
    focus_weeks: int = 2                          # default calendar: days for the current week + N weeks, then weeks

    def copy_with(self, **changes: Any) -> "EngineParams":
        data = self.__dict__.copy()
        data.update(changes)
        return EngineParams(**data)


# =============================================================================
# Outputs
# =============================================================================
class AlertType(str, Enum):
    STOCKOUT = "STOCKOUT"
    LOW_COVERAGE = "LOW_COVERAGE"
    OVERSTOCK = "OVERSTOCK"
    LATE_ORDER = "LATE_ORDER"
    URGENT_PROPOSAL = "URGENT_PROPOSAL"
    NO_DEMAND = "NO_DEMAND"
    MISSING_DATA = "MISSING_DATA"
    NEGATIVE_STOCK = "NEGATIVE_STOCK"


class Severity(str, Enum):
    CRITICAL = "critical"
    WARNING = "warning"
    INFO = "info"


@dataclass
class Alert:
    article_id: str
    alert_type: AlertType
    severity: Severity
    message: str
    date: dt.date | None = None
    value: float | None = None
    scope: Literal["erp", "plan", "data"] = "plan"
    details: dict[str, Any] = field(default_factory=dict)


@dataclass
class Proposal:
    proposal_id: str
    article_id: str
    supplier_id: str | None
    delivery_date: dt.date
    order_date: dt.date
    qty: float
    net_requirement: float
    reason: str
    urgent: bool = False
    lead_time_days: int = 0
    moq: float = 0.0
    pack_qty: float = 0.0
    projected_stock_before: float = 0.0
    projected_stock_after: float = 0.0


@dataclass
class SupplyEvent:
    """One dated supply element shown in the article table / tooltips."""

    date: dt.date
    kind: str               # order | plan | receipt | movement | proposal
    ref: str
    qty: float
    supplier_id: str | None
    order_type: str
    source: str
    late: bool = False


OrderStateStatus = Literal["expected", "planned", "not_received", "info"]


@dataclass
class OrderState:
    """One open ERP (or app) order – a delivery slot – as seen by the run.

    ``status``: ``expected`` (counted in the ERP stock at its date, and in the plan stock unless
    overridden), ``planned`` (overridden by plan lines), ``not_received`` (date past, still open
    in the ERP: excluded from every stock, to qualify), ``info`` (forecast: shown, not counted).
    """

    order_id: str
    article_id: str
    supplier_id: str | None
    order_type: str
    source: str
    expected_date: dt.date
    qty_ordered: float
    qty_open: float
    qty_expected: float             # counted in the ERP stock (after the same-day matching)
    days_late: int
    status: OrderStateStatus
    plan_qty: float = 0.0           # quantity of this order in the plan layer (after overrides)
    plan_dates: list[dt.date] = field(default_factory=list)
    note: str = ""


@dataclass
class PlanLineState:
    """One line of the delivery plan as displayed: stored lines, ERP orders taken as is, CBN."""

    line_id: str | None             # None: ERP order taken as is (not stored) or CBN proposal
    order_id: str | None
    article_id: str
    date: dt.date
    qty: float
    supplier_id: str | None
    origin: str                     # erp | override | free | cbn | expired
    counted: bool                   # in the plan stock
    erp_date: dt.date | None = None
    erp_qty: float | None = None
    note: str = ""


@dataclass
class ArticleResult:
    article: Article
    start_date: dt.date
    as_of: dt.date
    dates: list[dt.date]
    # daily series aligned on ``dates``
    demand: list[float]               # consumption (past, actual-based) + requirement (future)
    consumed: list[float]             # past part of ``demand`` (0 from the reference day)
    required: list[float]             # future part of ``demand`` (0 before the reference day)
    demand_plan: list[float]          # PDP only, for information
    demand_actual_share: list[float]
    orders_firm: list[float]          # ERP firm orders counted in the ERP stock (open, matched on the reference day)
    orders_firm_hist: list[float]     # past firm orders, ordered quantity (display only)
    orders_forecast: list[float]      # ERP forecast orders (information)
    receipts: list[float]             # receipts (past by construction, reference day included)
    plan: list[float]                 # delivery plan counted in the plan stock (ERP as is + lines), CBN excluded
    plan_hist: list[float]            # expired plan lines (display only)
    supply_proposed: list[float]      # CBN complement
    adjustments: list[float]          # planner adjustments (future days ; past ones correct the reference stock)
    reference_correction: float       # sum of the adjustments dated on/before the reference day
    # physical stocks (never negative), unserved demand and net balances per layer ; before the
    # reference day both layers hold the reconstructed history
    stock_erp: list[float]
    stock_plan: list[float]
    shortage_onhand: list[float]
    shortage_erp: list[float]
    shortage_plan: list[float]
    stock_erp_net: list[float]
    stock_plan_net: list[float]
    coverage_erp: list[int]
    coverage_plan: list[int]
    target_stock: list[float]
    events: list[SupplyEvent]
    alerts: list[Alert]
    proposals: list[Proposal]
    kpis: dict[str, Any]
    suppliers: list[SupplierLink]
    orders: list[OrderState] = field(default_factory=list)
    plan_lines: list[PlanLineState] = field(default_factory=list)
    diagnostics: list[str] = field(default_factory=list)


@dataclass
class MrpResult:
    as_of: dt.date
    start_date: dt.date
    end_date: dt.date
    params: EngineParams
    articles: dict[str, ArticleResult]
    program_daily: dict[str, dict[dt.date, float]]
    diagnostics: list[str] = field(default_factory=list)
    program_impact: dict[str, Any] = field(default_factory=dict)   # see engine/programs.py

    @property
    def alerts(self) -> list[Alert]:
        return [a for r in self.articles.values() for a in r.alerts]

    @property
    def proposals(self) -> list[Proposal]:
        return [p for r in self.articles.values() for p in r.proposals]
